name: 'carematrix_dbt'
version: '1.0.0'
config-version: 2

# This setting points dbt to the profile in profiles.yml
profile: 'carematrix_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  carematrix_dbt:
    # Config for all models
    +materialized: table
